### ISSUE TITLE
Locations issue

### ISSUE THREAD

**Issue by kvydiuk** [tcbgroup/dhl-service-point-locator#1]
Is it working only for Sweden? I've tried to use Hungary valid zip and country codes and didn't have any successful result. Also for any another countries... Thanks for this code, but would be great if other countries also being supported.

**Comment by murtlest** [comment]
The api that this library targets only supports service points in Sweden, unfortunately. 

Seems like it's possible to get information about non-swedish service points (not supported by library yet), but the endpoint for getting the closest service point only works for Sweden.
